feat: New action input parameter and linear backoff strategy for retries
Codex-/return-dispatch pull request #267
Opened 2024-12-20 12:39 UTC by Yermanaco

make WORKFLOW_JOB_STEPS_RETRY_MS variable as an action input parameter and linear backoff strategy for retries

2024-12-27 11:29 UTC, Yermanaco commented
@Codex- Tests The tests are passing now, and I noticed (if I'm not mistaken) that the token [access issue for the action](https://github.com/Codex-/return-dispatch/actions/runs/12503708658/job/34895368973?pr=267#step:5:13) is expected when triggered from a PR. What do you think about the PR? This new functionality would be very helpful for us. Thanks!

2024-12-27 12:00 UTC, Codex- commented
@Yermanaco will give a proper review when I can, thanks for the PR

Christmas and New Years period is always a bit chaotic 😅

2025-01-08 15:41 UTC, Yermanaco commented
> @Yermanaco will give a proper review when I can, thanks for the PR
> 
> Christmas and New Years period is always a bit chaotic 😅

Happy new Year @Codex- ! Just a kindly reminder 😄

2025-01-08 22:01 UTC, Codex- requested changes
Looking pretty good overall, just a couple of small things then I think we can get this released today

2025-01-08 22:01 UTC, Codex- commented on src/return-dispatch.spec.ts
> +      expect(utilSleepMock.mock.calls[2]?.[0]).toBeLessThanOrEqual(retryMs * 3);
```suggestion
      const elapsedTime = Date.now() - startTime; // `waitTime` should be using `workflowTimeoutMs` at this point
      expect(utilSleepMock.mock.lastCall?.[0]).approximately(
        timeoutMs - elapsedTime,
        5,
      );
```

2025-01-09 11:44 UTC, Yermanaco commented on src/return-dispatch.ts
> +      workflowJobStepsRetryMs * attemptNo, // Lineal backoff
changed in the readme and in the action description too

2025-01-09 11:44 UTC, Yermanaco commented on src/return-dispatch.spec.ts
> +      expect(utilSleepMock.mock.calls[2]?.[0]).toBeLessThanOrEqual(retryMs * 3);
nice approach!

2025-01-09 21:30 UTC, Codex- approved these changes
Great, thank you for contributing these changes ✨ 

I will comment on this PR when I've released them

2025-01-09 21:32 UTC, merged

2025-01-09 21:42 UTC, Codex- commented
Released, can be used with either the `v2` tag or `v2.0.4`